export enum SubscriptionPlan {
  STARTER = 'starter',
  GROWTH = 'growth',
  SCALE = 'scale',
}

export enum FeatureAccess {
  BASIC_HR = 'BASIC_HR',
  PAYROLL = 'PAYROLL',
  ATTENDANCE = 'ATTENDANCE',
  LEAVE_MANAGEMENT = 'LEAVE_MANAGEMENT',
  MULTI_CURRENCY = 'MULTI_CURRENCY',
  ADVANCED_ATTENDANCE = 'ADVANCED_ATTENDANCE',
  PERFORMANCE_MANAGEMENT = 'PERFORMANCE_MANAGEMENT',
  RECRUITMENT = 'RECRUITMENT',
  EMPLOYEE_SELF_SERVICE = 'EMPLOYEE_SELF_SERVICE',
  ADVANCED_REPORTING = 'ADVANCED_REPORTING',
  API_ACCESS = 'API_ACCESS',
  INTEGRATIONS = 'INTEGRATIONS',
  MULTI_LOCATION = 'MULTI_LOCATION',
  ADVANCED_PAYROLL = 'ADVANCED_PAYROLL',
  LEARNING_DEVELOPMENT = 'LEARNING_DEVELOPMENT',
  CUSTOM_WORKFLOWS = 'CUSTOM_WORKFLOWS',
  WHITE_LABEL = 'WHITE_LABEL',
  COMPLIANCE_REPORTING = 'COMPLIANCE_REPORTING',
}
