export const PAYROLL_SECURITY_CONFIG = {
  MAX_SALARY_LIMIT: 1000000, 
  MAX_PAYMENT_LIMIT: 100000, 
  MAX_EMPLOYEES_PER_RUN: 1000, 
  MIN_PAYMENT_AMOUNT: 0.01, 
  MIN_SALARY_AMOUNT: 1, 
  LARGE_PAYMENT_THRESHOLD: 10000, 
  SALARY_CHANGE_THRESHOLD: 0.5, 
  MAX_PAYROLL_PROCESSING_TIME: 3600000, 
  PAYROLL_LOCK_TIMEOUT: 300000, 
  MAX_PAYROLL_RUNS_PER_DAY: 10, 
  MAX_CALCULATION_RETRIES: 3, 
  SUPPORTED_CURRENCIES: [
    'USD',
    'EUR',
    'GBP',
    'CAD',
    'AUD',
    'JPY',
    'CHF',
    'SEK',
    'NOK',
    'DKK',
    'NGN',
    'GHS',
    'KES',
    'ZAR',
    'EGP',
    'MAD',
    'TND',
    'UGX',
    'TZS',
    'BTC',
    'ETH',
    'USDT',
    'USDC',
    'BNB',
    'ADA',
    'DOT',
    'SOL',
    'MATIC',
  ],
  EMPLOYEE_ID_PATTERN:
    /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i,
  PAYROLL_AUTHORIZED_ROLES: ['owner', 'admin'],
  PAYROLL_VIEW_ROLES: ['owner', 'admin', 'hr'],
  AUDIT_EVENTS: {
    PAYROLL_CREATED: 'payroll.created',
    PAYROLL_CALCULATED: 'payroll.calculated',
    PAYROLL_PROCESSED: 'payroll.processed',
    SALARY_ACCESSED: 'salary.accessed',
    PAYMENT_ATTEMPTED: 'payment.attempted',
    PAYMENT_FAILED: 'payment.failed',
    LARGE_PAYMENT_DETECTED: 'payment.large_amount',
    SUSPICIOUS_ACTIVITY: 'security.suspicious_activity',
  },
} as const;
export type PayrollSecurityConfig = typeof PAYROLL_SECURITY_CONFIG;
